### PR TITLE
Leave help message on screen

### PR DESCRIPTION
**Pull request by johncmerfeld**
Addressing #41 so that the message telling the user how to open the help menu doesn't disappear after they start scrolling.

### CODE REVIEW

**Review by kjmerf — APPROVED** [review]

**Comment by kjmerf** [comment]
Works great. The branch doesn't contain the most recent from master so I couldn't the test that the message showed with chunking but worked fine otherwise. Given the simplicity of the change, I'm okay going forward without testing the chunking case.

**Comment by kjmerf** [comment]
@johncmerfeld just realized this PR has a conflict...

**Comment by johncmerfeld** [comment]
> @johncmerfeld just realized this PR has a conflict...

Yep, fixed.

**Comment by kjmerf** [comment]
Interesting that I don't have to submit another approval despite the fact that you pushed another commit!

**Pull request merged**
