### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by baogorek**
- Addressed [Issue 2](https://github.com/baogorek/datascroller/issues/2) and [Issue 6](https://github.com/baogorek/datascroller/issues/6) about the error when the data frame string exceeded curses window dimension
- Addressed [Issue 8](https://github.com/baogorek/datascroller/issues/8) on long import statement
- Addressed [Issue 4](https://github.com/baogorek/datascroller/issues/4) on console ghosting.

### CODE REVIEW

**Comment by baogorek** [comment]
@johncmerfeld , I'm pretty happy with these last updates. Mind on taking them for a spin?

```
from datascroller import scroll
scroll(<your df>)
```

**Comment by johncmerfeld** [comment]
Awesome, will give these a try tomorrow!

**Comment by johncmerfeld** [comment]
Looks great, Ben!

  - It works regardless of whether I'm using iPython / regular Python, tmux / no tmux
    - Note that in non-interactive Python, telling the dataframe to print starting at `(0,0)` actually **does** make it appear at the very top left of the screen. I actually found this suboptimal, since as a developer I'm used to looking at the bottom of a terminal window for new information. Something to think about
  - No more crashing out when I try to scroll or expand past the edge of the dataframe or display window.
  - No ghosting or any weirdness whatsoever in the display, even right when `scroll` is called.

I've got some thoughts on the user experience of scrolling; more specifically the keybindings. My intuition is that we could switch from the Vim keybindings to an SEFD and JIKL setup (right hand scrolls the current window, left hand can modify it – both hands mimic the arrow key structure and neither hand has to move from its natural typing position). But I can put that in another branch and we'll experiment with it.

I think this is an awesome step forward!

**Comment by baogorek** [comment]
Created [Issue 12](https://github.com/baogorek/datascroller/issues/12), [Issue 13](https://github.com/baogorek/datascroller/issues/13) based on your comments above, @johncmerfeld. Thank you for the review!

**Pull request merged**
